# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pictrue',
            new_name='picture',
        ),
    ]
